name:                jimple2json
version:             0.0.1
github:              "rafaelsamenezes/jimple2json"
license:             MIT
author:              "Rafael Sá Menezes"
maintainer:          "rafael.sa.menezes@outlook.com"
copyright:           "2021 Rafael Sá Menezes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rafaelsamenezes/jimple2json#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - parsec
  - aeson
  - text

executables:
  jimple-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jimple2json
    - bytestring

tests:
  jimple-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jimple2json
    - bytestring
    - tasty
    - tasty-smallcheck
    - tasty-hunit
    - tasty-quickcheck
